version: "3.9"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8007:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  web:
    build: .
    command: bash -c "python manage.py makemigrations users sources dests transforms pipelines && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && sudo chmod 777 ./docker/dynamodb"
    # command: bash -c "python manage.py makemigrations users sources dests transforms pipelines && python manage.py migrate && python createDynamoTable.py && python manage.py runserver 0.0.0.0:8000"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./docker/data:/code"
    ports:
      - "8000:8000"
    depends_on:
      - dynamodb-local
      - db
  # db:
  #   image: postgres:14.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - 5434:5432
  #   volumes:
  #     - ./docker/postgres:/var/lib/postgresql/data
